### Create Game
POST http://localhost:3000/game
content-type: application/json

{
    "name": "Mobile Legend",
    "role": "admin"
}

### Create by forbidden role
POST http://localhost:3000/game
content-type: application/json

{
    "name": "Mobile Legend",
    "role": "player"
}


### Play game
POST http://localhost:3000/game/play
content-type: application/json

{
    "level": 3
}

### Play forbidden game
POST http://localhost:3000/game/play
content-type: application/json

{
    "level": 0
}


### Play premium Games
POST http://localhost:3000/game/premium
content-type: application/json

{
    "membership": "premium"
}

### Play forbidden premium Games
POST http://localhost:3000/game/premium
content-type: application/json

{
    "membership": "free"
}
